### PR TITLE
Upgrade client-go to version 6.

### PR DESCRIPTION
**Pull request by timoreimann**
Needs another update + squash once the release tags are available.

### CODE REVIEW

**Comment by nikhita** [comment]
Would need an update in the README as well. :)

**Comment by timoreimann** [comment]
Good point -- will do that later. :+1:

**Comment by timoreimann** [comment]
@nikhita the latest commit updates the README slightly. Not sure if it's good enough though.

WDYT?

**Comment by nikhita** [comment]
> WDYT?

lgtm. :+1:

**Comment by timoreimann** [comment]
@ncdc with release tags in place and the PR updated, we are now good to merge :)

**Pull request merged**
